spring:
    datasource:
        url: jdbc:mysql://localhost:3306/netperf?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            pool-name: HikariCP
            maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    address: 0.0.0.0
    port: 8080
knf:
    app:
        jwtExpirationMs: 76300000
        jwtSecret: knowledgeFactory